

import { GameState, LogEntry, PrizePool, InitialWorldConfig, Provider } from '../types';
import { initialWorldAttributes } from '../constants';
import { DEFAULT_API_CONFIG } from '../config';
import { generateInitialMap } from './mapUtils';
import { INITIAL_DEFAULT_SETTINGS } from './DefaultSettings';
import { DEFAULT_THEME_CONFIG } from './themeService';

export const createInitialGameState = (initialWorldConfig?: InitialWorldConfig): GameState => {
  const { map, characters } = generateInitialMap(initialWorldConfig || INITIAL_DEFAULT_SETTINGS.initialWorldConfig);
  
  const initialLog: LogEntry = {
      id: `log_init_${Date.now()}`,
      round: 1,
      turnIndex: 0,
      content: "系统: 欢迎使用花海引擎。",
      timestamp: Date.now(),
      type: 'system',
      snapshot: {
          roundNumber: 1, turnIndex: 0, phase: 'init', currentOrder: [], defaultOrder: [], 
          isReverse: false, isPaused: true, autoAdvance: false, autoAdvanceCount: 0, actionPoints: 50
      }
  };

  const startLog: LogEntry = {
      id: `log_start_${Date.now()}`,
      round: 1,
      turnIndex: 0,
      content: "--- 第 1 轮 开始 ---",
      timestamp: Date.now() + 1,
      type: 'system',
      snapshot: {
          roundNumber: 1, turnIndex: 0, phase: 'init', currentOrder: [], defaultOrder: [], 
          isReverse: false, isPaused: true, autoAdvance: false, autoAdvanceCount: 0, actionPoints: 50
      }
  };

  // Ensure we use the actual ID generated by generateInitialMap
  const startLocId = map.activeLocationId || Object.keys(map.locations)[0];

  const defaultPrizePool: PrizePool = {
      id: `pool_${Date.now()}`,
      name: '神秘补给箱',
      description: '散落在世界各地的旧世界补给箱，里面可能含有有用的物资，也可能只有垃圾。',
      locationIds: [startLocId],
      items: [
          { id: 'item_01', name: '过期罐头', description: '虽然过期了，但也许还能吃...', weight: 50 },
          { id: 'item_02', name: '生锈的匕首', description: '一把勉强能用的防身武器。', weight: 30 },
          { id: 'item_03', name: '急救包', description: '珍贵的医疗物资。', weight: 15 },
          { id: 'item_04', name: '旧世界芯片', description: '珍贵的科技数据。', weight: 5 }
      ]
  };

  return {
    world: {
      attributes: initialWorldAttributes,
      history: [startLog, initialLog],
      worldGuidance: "写实风格的世界探索。",
      storyTags: [],
      lastFunSuggest: "",
      activeLanguageConditions: []
    },
    map,
    round: {
      roundNumber: 1,
      turnIndex: 0,
      phase: 'init',
      defaultOrder: [],
      currentOrder: [],
      isReverse: false,
      isPaused: true,
      autoAdvance: false,
      autoAdvanceCount: 0,
      actionPoints: 50,
      lastErrorMessage: undefined,
      useManualTurnOrder: false,
      isWaitingForManualOrder: false,
      skipSettlement: false,
      autoReaction: false, // Default to Manual Reaction
      isWorldTimeFlowPaused: true
    },
    characters,
    cardPool: [],
    prizePools: {
        [defaultPrizePool.id]: defaultPrizePool
    },
    triggers: {},
    triggerGroups: {}, // New
    judgeConfig: {
      provider: Provider.VOLCANO,
      model: 'doubao-seed-1-8-251228',
      temperature: 1
    },
    charGenConfig: {
      provider: Provider.VOLCANO,
      model: 'doubao-seed-1-8-251228',
      temperature: 1
    },
    charBehaviorConfig: {
      provider: Provider.VOLCANO,
      model: 'doubao-seed-1-8-251228',
      temperature: 1,
      readerComments: [],
      pureComments: []
    },
    globalContext: {
        messages: []
    },
    appSettings: {
        apiKeys: DEFAULT_API_CONFIG,
        customEndpoints: [], // Initialize custom endpoints list
        maxOutputTokens: 20000, 
        maxInputTokens: 64000, 
        reactionContextTurns: 5,
        devOptionsUnlocked: false,
        devPassword: "",
        encryptSaveFiles: false,
        maxHistoryRounds: 20,
        maxShortHistoryRounds: 5,
        maxCharacterMemoryRounds: 7, 
        maxEnvMemoryRounds: 5, // Default 5 for env
        actionMemoryDropoutProbability: 0.34, // Default Action Dropout
        reactionMemoryDropoutProbability: 0.34, // Default Reaction Dropout
        saveExpirationDate: "",
        globalVariables: [],
        storyLogLightMode: false,
        storyLogFontSize: 14,
        storyLogFontWeight: 500,
        themeConfig: DEFAULT_THEME_CONFIG,
        lockedFeatures: {
            cardPoolEditor: false,
            characterEditor: false,
            locationEditor: false,
            actionPoints: false,
            worldState: false,
            directorInstructions: false,
            prizePoolEditor: false,
            triggerEditor: false,
            mapView: false,
            modelInterface: false
        },
        imageSettings: {
            maxShortEdge: 896,
            maxLongEdge: 4480,
            compressionQuality: 0.95
        },
        useNativeChooser: false,
        enableStreaming: true,
        autoScrollOnNewLog: false,
        showHiddenRoundContent: false
    },
    defaultSettings: INITIAL_DEFAULT_SETTINGS,
    devMode: false,
    debugLogs: []
  };
};
